export default [
  "Full Stack JavaScript Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Front-end Developer",
  "Back-end Developer",
  "Web Developer",
  "CTO",
  "Software Engineer",
  "AWS (Amazon Web Services)",
  "EC2 (Elastic Compute Cloud)",
  "Digital Ocean",
  "Responsive Web Design",
  "Mobile App Development",
  "API Development",
  "Database Management",
  "Agile Development",
  "MVC Architecture",
  "Git Version Control",
  "HTML5",
  "CSS3",
  "Node.js",
  "Express.js",
  "React.js",
  "AngularJS",
  "Vue.js",
  "RESTful APIs",
  "Serverless Architecture",
  "Cloud Deployment",
  "DevOps",
  "Test-driven Development (TDD)",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Scalable Web Applications",
  "Performance Optimization",
  "User Experience (UX)",
  "UI/UX Design",
  "Problem-solving",
  "Team Leadership",
  "Project Management",
  "Agile Methodologies",
  "Client Communication",
  "Portfolio Showcase",
  "Professional Experience",
  "Skills and Expertise",
  "Projects and Case Studies",
  "Testimonials",
  "Contact Information",
  "Blog",
  "Technical Blog Posts",
  "GitHub Profile",
  "LinkedIn Profile",
];
